package com.example.typesense.model;



public enum InvoiceStatus {
    RECEIVED, ENRICHED, PENDING_VALIDATION, PENDING_COMPLIANCE, READY_FOR_PROCESS, PENDING_MATCHING, PROCESSED,
    IN_PROCESS, ON_HOLD, PENDING_ERP_MANDATORY_FIELDS, INITIATE_APPROVAL, PENDING_APPROVAL, APPROVAL_REJECTED,
    READY_FOR_ERP, QUEUED_TO_ERP, SENT_TO_ERP, PAID, CANCELLED_IN_ERP, POSTED_TO_ERP, PARTIALLY_PAID, REJECTED,
    ISSUES_IN_ERP, PARKED_IN_ERP, SENT_BACK_FROM_ERP, SOFT_DELETED, READY_TO_POST;


}